name: cron

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13,17,18,22 * * 1-5'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn ci
    - run: yarn cypress run --record --key ${{ secrets.RECORD_KEY }}
      env:
        CYPRESS_USER: ${{ secrets.CYPRESS_USER }}
        CYPRESS_PASS: ${{ secrets.CYPRESS_PASS }}
        CYPRESS_PAY_MF_PRO: ${{ secrets.PAY_MF_PRO }}
        